import os
from datetime import datetime
from typing import Dict, List


def generate_onboarding_html(
    summaries: Dict[str, str],
    repo_meta: Dict[str, str],
    author: str = "AI Assistant",
    company: str = "Your Company"
) -> str:
    """
    Generate a professional HTML onboarding document with:
    - Cover page
    - Table of contents  
    - Section-by-section content
    - Professional CSS styling
    """
    
    # Extract repo info
    repo_name = repo_meta.get("repo", "Repository")
    owner = repo_meta.get("owner", "Unknown")
    github_url = f"https://github.com/{owner}/{repo_name}"
    current_date = datetime.now().strftime("%B %d, %Y")
    
    # Generate table of contents
    toc_items = []
    section_content = []
    
    for i, (file_path, summary) in enumerate(summaries.items(), 1):
        section_id = f"section-{i}"
        # Clean up file path for display
        display_name = file_path.replace("/", " / ").replace("_", " ").replace("-", " ")
        
        toc_items.append(f'<li><a href="#{section_id}">{display_name}</a></li>')
        
        # Create section content
        section_content.append(f'''
        <div class="section" id="{section_id}">
            <h2 class="section-title">{display_name}</h2>
            <div class="section-path">📁 {file_path}</div>
            <div class="section-content">
                {format_summary_content(summary)}
            </div>
        </div>
        ''')
    
    # Build complete HTML
    html_template = f'''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{repo_name} - Onboarding Documentation</title>
    <style>
        {get_css_styles()}
    </style>
</head>
<body>
    <!-- Cover Page -->
    <div class="cover-page">
        <div class="cover-header">
            <div class="company-branding">
                <h1 class="company-name">{company}</h1>
                <div class="company-tagline">Knowledge Base Documentation</div>
            </div>
        </div>
        
        <div class="cover-main">
            <h1 class="project-title">{repo_name}</h1>
            <h2 class="subtitle">Onboarding Documentation</h2>
            
            <div class="project-info">
                <div class="info-item">
                    <span class="label">Repository:</span>
                    <a href="{github_url}" target="_blank" class="repo-link">{github_url}</a>
                </div>
                <div class="info-item">
                    <span class="label">Author:</span>
                    <span class="value">{author}</span>
                </div>
                <div class="info-item">
                    <span class="label">Generated:</span>
                    <span class="value">{current_date}</span>
                </div>
                <div class="info-item">
                    <span class="label">Branch:</span>
                    <span class="value">{repo_meta.get("branch", "main")}</span>
                </div>
            </div>
        </div>
        
        <div class="cover-footer">
            <p>This document provides an overview of the repository structure and key documentation files.</p>
        </div>
    </div>

    <!-- Table of Contents Page -->
    <div class="toc-page">
        <h1 class="page-title">Table of Contents</h1>
        <div class="toc-summary">
            <p>This document contains <strong>{len(summaries)}</strong> sections covering the main documentation files in the repository.</p>
        </div>
        <ul class="toc-list">
            {"".join(toc_items)}
        </ul>
    </div>

    <!-- Content Sections -->
    <div class="content-pages">
        {"".join(section_content)}
    </div>

    <!-- Footer -->
    <div class="document-footer">
        <p>Generated by AI-Powered Onboarding Documentation System</p>
        <p>For the most up-to-date information, please refer to the repository at <a href="{github_url}">{github_url}</a></p>
    </div>
</body>
</html>
'''
    
    return html_template


def format_summary_content(summary: str) -> str:
    """Format summary content with proper HTML markup"""
    # Split into paragraphs
    paragraphs = summary.split('\n\n')
    formatted_paragraphs = []
    
    for para in paragraphs:
        para = para.strip()
        if not para:
            continue
            
        # Check for special formatting
        if para.startswith("Note:"):
            formatted_paragraphs.append(f'<div class="note">{para}</div>')
        elif para.startswith("For full details"):
            formatted_paragraphs.append(f'<div class="reference">{para}</div>')
        else:
            formatted_paragraphs.append(f'<p>{para}</p>')
    
    return "".join(formatted_paragraphs)


def get_css_styles() -> str:
    """Return comprehensive CSS styles for the onboarding document"""
    return '''
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #ffffff;
        }

        /* Cover Page Styles */
        .cover-page {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 60px 40px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            page-break-after: always;
        }

        .cover-header {
            text-align: right;
        }

        .company-branding .company-name {
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 5px;
        }

        .company-tagline {
            font-size: 1.1rem;
            opacity: 0.9;
        }

        .cover-main {
            text-align: center;
            flex: 1;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }

        .project-title {
            font-size: 4rem;
            font-weight: 800;
            margin-bottom: 20px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }

        .subtitle {
            font-size: 1.8rem;
            font-weight: 300;
            margin-bottom: 60px;
            opacity: 0.9;
        }

        .project-info {
            background: rgba(255,255,255,0.1);
            padding: 30px;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            max-width: 600px;
            margin: 0 auto;
        }

        .info-item {
            display: flex;
            justify-content: space-between;
            margin-bottom: 15px;
            padding: 8px 0;
            border-bottom: 1px solid rgba(255,255,255,0.2);
        }

        .info-item:last-child {
            border-bottom: none;
        }

        .label {
            font-weight: 600;
        }

        .value {
            font-weight: 400;
        }

        .repo-link {
            color: #ffffff;
            text-decoration: none;
            border-bottom: 1px dotted rgba(255,255,255,0.5);
        }

        .repo-link:hover {
            border-bottom: 1px solid rgba(255,255,255,0.8);
        }

        .cover-footer {
            text-align: center;
            font-size: 1.1rem;
            opacity: 0.8;
        }

        /* Table of Contents Styles */
        .toc-page {
            min-height: 100vh;
            padding: 60px 40px;
            page-break-after: always;
        }

        .page-title {
            font-size: 3rem;
            font-weight: 700;
            color: #2d3748;
            margin-bottom: 30px;
            text-align: center;
        }

        .toc-summary {
            text-align: center;
            margin-bottom: 50px;
            font-size: 1.1rem;
            color: #666;
        }

        .toc-list {
            list-style: none;
            max-width: 800px;
            margin: 0 auto;
        }

        .toc-list li {
            margin-bottom: 15px;
            padding: 15px 20px;
            background: #f7fafc;
            border-radius: 8px;
            border-left: 4px solid #667eea;
        }

        .toc-list a {
            text-decoration: none;
            color: #2d3748;
            font-size: 1.1rem;
            font-weight: 500;
        }

        .toc-list a:hover {
            color: #667eea;
        }

        /* Content Section Styles */
        .content-pages {
            max-width: 900px;
            margin: 0 auto;
            padding: 40px;
        }

        .section {
            margin-bottom: 60px;
            padding-bottom: 40px;
            border-bottom: 2px solid #e2e8f0;
            page-break-inside: avoid;
        }

        .section:last-child {
            border-bottom: none;
        }

        .section-title {
            font-size: 2rem;
            font-weight: 700;
            color: #2d3748;
            margin-bottom: 10px;
        }

        .section-path {
            font-family: 'Courier New', monospace;
            font-size: 0.9rem;
            color: #666;
            background: #f7fafc;
            padding: 8px 12px;
            border-radius: 5px;
            margin-bottom: 25px;
            display: inline-block;
        }

        .section-content {
            font-size: 1.1rem;
            line-height: 1.7;
        }

        .section-content p {
            margin-bottom: 15px;
        }

        .note {
            background: #fff5cd;
            border: 1px solid #f6e05e;
            border-radius: 5px;
            padding: 15px;
            margin: 20px 0;
            font-style: italic;
        }

        .reference {
            background: #e6fffa;
            border: 1px solid #81e6d9;
            border-radius: 5px;
            padding: 12px;
            margin: 15px 0;
            font-size: 0.95rem;
        }

        /* Footer Styles */
        .document-footer {
            background: #f7fafc;
            padding: 30px;
            text-align: center;
            color: #666;
            border-top: 2px solid #e2e8f0;
            margin-top: 60px;
        }

        .document-footer p {
            margin-bottom: 10px;
        }

        .document-footer a {
            color: #667eea;
            text-decoration: none;
        }

        /* Print Styles */
        @media print {
            .cover-page,
            .toc-page {
                page-break-after: always;
            }
            
            .section {
                page-break-inside: avoid;
            }
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            .cover-page,
            .toc-page,
            .content-pages {
                padding: 30px 20px;
            }
            
            .project-title {
                font-size: 2.5rem;
            }
            
            .page-title {
                font-size: 2rem;
            }
            
            .info-item {
                flex-direction: column;
                gap: 5px;
            }
        }
    '''


def save_html_file(html_content: str, filename: str = "onboarding_document.html") -> str:
    """Save HTML content to file and return the file path"""
    filepath = os.path.abspath(filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    return filepath
